INSERT INTO books (title, author, average_rating, number_of_pages) VALUES 
('The John Milton Series: Books 1-3','Mark Dawson',4.06,873),
('In the Blink of an Eye','Walter Murch',4.24,148),
('Save the Cat!: The Last Book on Screenwriting You''ll Ever Need','Blake Snyder',4.05,191),
('Rebel Without a Crew, or How a 23-Year-Old Filmmaker With $7,000 Became a Hollywood Player','Robert Rodríguez',4.13,304),
('Fugitives and Refugees: A Walk in Portland, Oregon','Chuck Palahniuk',3.51,176),
('Doomed (Damned, #2)','Chuck Palahniuk',3.27,336),
('Tell-All','Chuck Palahniuk',2.84,192),
('Over the Edge of the World: Magellan''s Terrifying Circumnavigation of the Globe','Laurence Bergreen',4.09,438),
('The Great Sea: A Human History of the Mediterranean','David Abulafia',3.88,783),
('Argo: How the CIA & Hollywood Pulled Off the Most Audacious Rescue in History','Antonio J. Méndez',3.83,310),
('Beyond Band of Brothers: The War Memoirs of Major Dick Winters','Dick Winters',4.25,304),
('Millennium: The End of the World and the Forging of Christendom','Tom Holland',3.82,476),
('The Looming Tower: Al-Qaeda and the Road to 9/11','Lawrence Wright',4.38,373),
('Made in America: An Informal History of the English Language in the United States','Bill Bryson',3.9,415),
('The Better Angels of Our Nature: Why Violence Has Declined','Steven Pinker',4.2,806),
('American Sphinx: The Character of Thomas Jefferson','Joseph J. Ellis',3.9,440),
('Lost in Shangri-la: A True Story of Survival, Adventure, and the Most Incredible Rescue Mission of World War II','Mitchell Zuckoff',3.83,384),
('On Tyranny: Twenty Lessons from the Twentieth Century','Timothy Snyder',4.26,128),
('The Coming of the Third Reich','Richard J. Evans',4.23,622),
('The Warmth of Other Suns: The Epic Story of America''s Great Migration','Isabel Wilkerson',4.32,622),
('The Age of Wonder: How the Romantic Generation Discovered the Beauty and Terror of Science','Richard  Holmes',3.95,380),
('The Fall of Berlin 1945','Antony Beevor',4.27,490),
('Ghost Soldiers: The Epic Account of World War II''s Greatest Rescue Mission','Hampton Sides',4.18,344),
('The Fatal Shore: The Epic of Australia''s Founding','Robert Hughes',4.06,688),
('Cod: A Biography of the Fish that Changed the World','Mark Kurlansky',3.91,294),
('The Radium Girls: The Dark Story of America''s Shining Women','Kate  Moore',4.25,480),
('A Peace to End All Peace: The Fall Of The Ottoman Empire And The Creation Of The Modern Middle East','David Fromkin',4.17,635),
('1421: The Year China Discovered America','Gavin Menzies',3.59,650),
('Debt: The First 5,000 Years','David Graeber',4.17,534),
('Persian Fire: The First World Empire and the Battle for the West','Tom Holland',4.16,418),
('Thunderstruck','Erik Larson',3.68,463),
('Europe','Norman Davies',4.17,1392),
('Liar, Temptress, Soldier, Spy: Four Women Undercover in the Civil War','Karen Abbott',3.76,513),
('Lawrence in Arabia: War, Deceit, Imperial Folly, and the Making of the Modern Middle East','Scott Anderson',4.13,577),
('Legacy of Ashes: The History of the CIA','Tim Weiner',3.89,702),
('Dead Wake: The Last Crossing of the Lusitania','Erik Larson',4.07,430),
('A History of the World in 100 Objects','Neil MacGregor',4.18,707),
('The Silk Roads: A New History of the World','Peter Frankopan',4.25,636),
('The First World War','John Keegan',4.01,475),
('The Great Influenza: The Story of the Deadliest Pandemic in History','John M. Barry',3.95,560),
('The Girls of Atomic City: The Untold Story of the Women Who Helped Win World War II','Denise Kiernan',3.67,373),
('The Witches: Salem, 1692','Stacy Schiff',3.13,512),
('All the President''s Men','Carl Bernstein',4.17,480),
('Manhunt: The 12-Day Chase for Lincoln''s Killer','James L. Swanson',4.13,434),
('The Bully Pulpit: Theodore Roosevelt, William Howard Taft, and the Golden Age of Journalism','Doris Kearns Goodwin',4.17,910),
('The River of Doubt: Theodore Roosevelt''s Darkest Journey','Candice Millard',4.16,416),
('Empire of the Summer Moon: Quanah Parker and the Rise and Fall of the Comanches, the Most Powerful Indian Tribe in American History','S.C. Gwynne',4.13,384),
('Gods and Generals (The Civil War Trilogy, #1)','Jeff Shaara',4.05,498),
('The Plantagenets: The Warrior Kings and Queens Who Made England','Dan Jones',4.17,534),
('Isaac''s Storm: A Man, a Time, and the Deadliest Hurricane in History','Erik Larson',4.05,336),
('The Monuments Men: Allied Heroes, Nazi Thieves, and the Greatest Treasure Hunt in History','Robert M. Edsel',3.74,473),
('Stalingrad: The Fateful Siege, 1942–1943','Antony Beevor',4.29,494),
('Rubicon: The Last Years of the Roman Republic','Tom Holland',4.17,464),
('The Swerve: How the World Became Modern','Stephen Greenblatt',3.84,356),
('Mayflower: A Story of Courage, Community, and War','Nathaniel Philbrick',3.86,461),
('The Ghost Map: The Story of London''s Most Terrifying Epidemic - and How It Changed Science, Cities, and the Modern World','Steven Johnson',3.91,299),
('Undaunted Courage: The Pioneering First Mission to Explore America''s Wild Frontier','Stephen E. Ambrose',4.22,592),
('Founding Brothers: The Revolutionary Generation','Joseph J. Ellis',3.92,290),
('Genghis Khan and the Making of the Modern World','Jack Weatherford',4.01,312),
('SPQR: A History of Ancient Rome','Mary Beard',4.09,608),
('Non-Fiction','Chuck Palahniuk',3.57,253),
('Damned (Damned, #1)','Chuck Palahniuk',3.38,256),
('Diary','Chuck Palahniuk',3.61,262),
('Rant','Chuck Palahniuk',3.82,320),
('Snuff','Chuck Palahniuk',3.18,208),
('Haunted','Chuck Palahniuk',3.59,419),
('Lullaby','Chuck Palahniuk',3.73,260),
('The Spy Who Came In from the Cold','John le Carré',4.07,224),
('State of Fear','Michael Crichton',3.69,672),
('Pines (Wayward Pines, #1)','Blake Crouch',3.89,305),
('Mr. Mercedes (Bill Hodges Trilogy, #1)','Stephen King',3.93,436),
('Prey','Michael Crichton',3.73,507),
('Relic (Pendergast, #1)','Douglas Preston',4.01,480),
('Confessions of an Economic Hit Man','John Perkins',3.84,303),
('The Sixth Extinction: An Unnatural History','Elizabeth Kolbert',4.11,336),
('Writing Down the Bones: Freeing the Writer Within','Natalie Goldberg',4.18,312),
('Death by Black Hole: And Other Cosmic Quandaries','Neil deGrasse Tyson',4.11,384),
('Matterhorn','Karl Marlantes',4.24,663),
('Black Hawk Down','Mark Bowden',4.28,320),
('Band of Brothers: E Company, 506th Regiment, 101st Airborne from Normandy to Hitler''s Eagle''s Nest','Stephen E. Ambrose',4.42,432),
('Food Rules: An Eater''s Manual','Michael Pollan',3.99,140),
('The Rise and Fall of the Third Reich: A History of Nazi Germany','William L. Shirer',4.15,1614),
('The Signal and the Noise: Why So Many Predictions Fail - But Some Don''t','Nate Silver',3.97,544),
('In the Garden of Beasts: Love, Terror, and an American Family in Hitler''s Berlin','Erik Larson',3.82,448),
('Salt Sugar Fat: How the Food Giants Hooked Us','Michael Moss',3.98,446),
('Zealot: The Life and Times of Jesus of Nazareth','Reza Aslan',3.83,296),
('The Reason I Jump: The Inner Voice of a Thirteen-Year-Old Boy with Autism','Naoki Higashida',3.78,135),
('The Poisoner''s Handbook: Murder and the Birth of Forensic Medicine in Jazz Age New York','Deborah Blum',3.99,319),
('Killers of the Flower Moon: The Osage Murders and the Birth of the FBI','David Grann',4.14,359),
('Julie and Julia: 365 Days, 524 Recipes, 1 Tiny Apartment Kitchen: How One Girl Risked Her Marriage, Her Job, and Her Sanity to Master the Art of Living','Julie Powell',3.68,310),
('Evicted: Poverty and Profit in the American City','Matthew Desmond',4.48,418),
('Smoke Gets in Your Eyes: And Other Lessons from the Crematory','Caitlin Doughty',4.09,272),
('Going Clear: Scientology, Hollywood, and the Prison of Belief','Lawrence Wright',4.02,430),
('Spook: Science Tackles the Afterlife','Mary Roach',3.57,311),
('The Disappearing Spoon: And Other True Tales of Madness, Love, and the History of the World from the Periodic Table of the Elements','Sam Kean',3.9,394),
('Astrophysics for People in a Hurry','Neil deGrasse Tyson',4.13,222),
('Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live, Love, Parent, and Lead','Brené Brown',4.24,287),
('The New Jim Crow: Mass Incarceration in the Age of Colorblindness','Michelle Alexander',4.5,290),
('So You''ve Been Publicly Shamed','Jon Ronson',3.93,290),
('Bird by Bird: Some Instructions on Writing and Life','Anne Lamott',4.23,237),
('god is Not Great: How Religion Poisons Everything','Christopher Hitchens',3.96,307),
('The Lost City of Z: A Tale of Deadly Obsession in the Amazon','David Grann',3.86,352),
('Eating Animals','Jonathan Safran Foer',4.19,341),
('Being Mortal: Medicine and What Matters in the End','Atul Gawande',4.42,282),
('The Emperor of All Maladies: A Biography of Cancer','Siddhartha Mukherjee',4.29,571),
('Nothing to Envy: Ordinary Lives in North Korea','Barbara Demick',4.43,316),
('The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing','Marie Kondō',3.78,224),
('My Life','Bill Clinton',3.72,1056),
('No One Here Gets Out Alive','Danny Sugerman',3.93,384),
('American Prometheus: The Triumph and Tragedy of J. Robert Oppenheimer','Kai Bird',4.15,725),
('Mountains Beyond Mountains: The Quest of Dr. Paul Farmer, A Man Who Would Cure the World','Tracy Kidder',4.21,333),
('Lincoln','David Herbert Donald',4.18,720),
('Escape from Camp 14: One Man''s Remarkable Odyssey from North Korea to Freedom in the West','Blaine Harden',4,205),
('Destiny of the Republic: A Tale of Madness, Medicine and the Murder of a President','Candice Millard',4.19,339),
('Mornings on Horseback: The Story of an Extraordinary Family, a Vanished Way of Life, and the Unique Child Who Became Theodore Roosevelt','David McCullough',4.11,445),
('On Writing: A Memoir of the Craft','Stephen King',4.32,320),
('Titan: The Life of John D. Rockefeller, Sr.','Ron Chernow',4.19,832),
('American Lion: Andrew Jackson in the White House','Jon Meacham',3.77,361),
('His Excellency: George Washington','Joseph J. Ellis',3.9,352),
('Thomas Jefferson: The Art of Power','Jon Meacham',3.98,759),
('Born Standing Up: A Comic''s Life','Steve Martin',3.87,207),
('Theodore Rex','Edmund Morris',4.16,772),
('Einstein: His Life and Universe','Walter Isaacson',4.09,551),
('Narrative of the Life of Frederick Douglass','Frederick Douglass',3.97,158),
('The Wright Brothers','David McCullough',4.15,320),
('Washington: A Life','Ron Chernow',4.08,927),
('Benjamin Franklin: An American Life','Walter Isaacson',3.98,493),
('The Rise of Theodore Roosevelt','Edmund Morris',4.25,780),
('Into the Darkest Corner','Elizabeth Haynes',4.1,410),
('Mr. Perfect','Linda Howard',4.06,405),
('The Sellout','Paul Beatty',3.78,304),
('Going Bovine','Libba Bray',3.65,480),
('Don''t Get Too Comfortable: The Indignities of Coach Class, The Torments of Low Thread Count, The Never-Ending Quest for Artisanal Olive Oil, and Other First World Problems','David Rakoff',3.71,222),
('The Know-It-All: One Man''s Humble Quest to Become the Smartest Person in the World','A.J. Jacobs',3.77,389),
('The Darwin Awards: Evolution in Action (Darwin Awards, #1)','Wendy Northcutt',3.66,352),
('Sleepwalk With Me and Other Painfully True Stories','Mike Birbiglia',3.86,191),
('American on Purpose: The Improbable Adventures of an Unlikely Patriot','Craig Ferguson',3.96,268),
('Rush Limbaugh Is a Big Fat Idiot','Al Franken',3.92,313),
('Year Zero','Rob  Reid',3.61,364),
('We Thought You Would Be Prettier: True Tales of the Dorkiest Girl Alive','Laurie Notaro',3.91,223),
('You''ll Grow Out of It','Jessi Klein',3.82,291),
('Theft by Finding: Diaries 1977-2002','David Sedaris',3.97,514),
('The Secret Diary of Adrian Mole, Aged 13 3/4  (Adrian Mole, #1)','Sue Townsend',3.86,272),
('Plato and a Platypus Walk Into a Bar: Understanding Philosophy Through Jokes','Thomas Cathcart',3.78,200),
('We Are Never Meeting In Real Life','Samantha Irby',3.96,288),
('Welcome to Night Vale (Night Vale, #1)','Joseph Fink',3.86,401),
('People I Want to Punch in the Throat: Competitive Crafters, Drop-Off Despots, and Other Suburban Scourges','Jen Mann',3.62,208),
('Why We Suck: A Feel Good Guide to Staying Fat, Loud, Lazy and Stupid','Denis Leary',3.67,240),
('Paddle Your Own Canoe: One Man''s Fundamentals for Delicious Living','Nick Offerman',3.65,340),
('I Know I Am, But What Are You?','Samantha Bee',3.56,242),
('Zombie Spaceship Wasteland','Patton Oswalt',3.57,191),
('Doomsday Book (Oxford Time Travel, #1)','Connie Willis',4.03,578),
('I Am America (And So Can You!)','Stephen Colbert',3.91,230),
('This is a Book','Demetri Martin',3.76,269),
('I Work at a Public Library: A Collection of Crazy Stories from the Stacks','Gina Sheridan',3.72,160),
('Stormy Weather','Carl Hiaasen',3.94,388),
('Basket Case','Carl Hiaasen',3.81,400),
('Star Island (Skink, #6)','Carl Hiaasen',3.44,337),
('Strip Tease','Carl Hiaasen',3.83,464),
('Razor Girl','Carl Hiaasen',3.81,335),
('Double Whammy','Carl Hiaasen',3.92,404),
('Lucky You','Carl Hiaasen',3.84,496),
('Skink--No Surrender (Skink #7)','Carl Hiaasen',3.92,281),
('The Downhill Lie: A Hacker''s Return to a Ruinous Sport','Carl Hiaasen',3.45,224),
('Flush','Carl Hiaasen',3.87,263),
('Bad Monkey','Carl Hiaasen',3.67,317),
('The Grass Is Always Greener over the Septic Tank','Erma Bombeck',4.1,256),
('A Short History of Nearly Everything','Bill Bryson',4.19,544),
('Naked Pictures of Famous People','Jon Stewart',3.59,164),
('One More Thing: Stories and Other Stories','B.J. Novak',3.66,288),
('Wishful Drinking','Carrie Fisher',3.75,163),
('The Bedwetter: Stories of Courage, Redemption, and Pee','Sarah Silverman',3.52,240),
('The Martian','Andy Weir',4.4,369),
('The Absolutely True Diary of a Part-Time Indian','Sherman Alexie',4.12,230),
('The Blackhouse (Lewis Trilogy, #1)','Peter  May',4.05,432),
('The Shining Girls','Lauren Beukes',3.49,375),
('The Killer Inside Me','Jim Thompson',3.89,244),
('The Postman Always Rings Twice','James M. Cain',3.81,116),
('The Hypnotist (Joona Linna, #1)','Lars Kepler',3.65,503),
('The Dry (Aaron Falk, #1)','Jane Harper',4.06,352),
('Blindsighted (Grant County, #1)','Karin Slaughter',4.1,418),
('Rivers of London (Peter Grant, #1)','Ben Aaronovitch',3.92,392),
('The Talented Mr. Ripley (Ripley, #1)','Patricia Highsmith',3.93,273),
('Case Histories (Jackson Brodie #1)','Kate Atkinson',3.82,389),
('The Name of the Rose','Umberto Eco',4.11,536),
('Knots and Crosses (Inspector Rebus, #1)','Ian Rankin',3.84,228),
('The Keeper of Lost Causes (Department Q, #1)','Jussi Adler-Olsen',3.98,395),
('The Ice Princess (Patrik Hedström, #1)','Camilla Läckberg',3.7,393),
('The Maltese Falcon','Dashiell Hammett',3.92,213),
('Faceless Killers (Kurt Wallander, #1)','Henning Mankell',3.77,280),
('Déjà Dead (Temperance Brennan, #1)','Kathy Reichs',3.86,532),
('The Bat (Harry Hole, #1)','Jo Nesbø',3.56,369),
('Room Full of Mirrors: A Biography of Jimi Hendrix','Charles R. Cross',4.14,400),
('Mo'' Meta Blues: The World According to Questlove','Ahmir Questlove Thompson',4.09,288),
('A History of Western Music','Donald Jay Grout',3.93,1136),
('Who I Am','Pete Townshend',3.68,538),
('The Real Frank Zappa Book','Frank Zappa',4.15,352),
('Retromania: Pop Culture''s Addiction to Its Own Past','Simon Reynolds',3.82,458),
('Lords of Chaos: The Bloody Rise of the Satanic Metal Underground','Michael Moynihan',3.76,391),
('Can''t Stop Won''t Stop: A History of the Hip-Hop Generation','Jeff Chang',4.14,546),
('Get in the Van: On the Road With Black Flag','Henry Rollins',4.09,303),
('I Am Ozzy','Ozzy Osbourne',4.06,391),
('The Heroin Diaries: A Year In The Life Of A Shattered Rock Star','Nikki Sixx',4.12,413),
('Orange Is the New Black','Piper Kerman',3.7,298);
INSERT INTO favs (title, author, average_rating, number_of_pages) VALUES
('The Magicians (The Magicians #1)','Lev Grossman',3.49,402),
('Nickel and Dimed: On (Not) Getting by in America','Barbara Ehrenreich',3.6,240),
('A People''s History of the United States','Howard Zinn',4.07,729),
('Patriot Games (Jack Ryan Universe, #2)','Tom Clancy',4.11,503),
('The Storied Life of A.J. Fikry','Gabrielle Zevin',3.98,260),
('Definitely Dead (Sookie Stackhouse, #6)','Charlaine Harris',4.02,342),
('Fast Food Nation: The Dark Side of the All-American Meal','Eric Schlosser',3.73,399),
('The Omnivore''s Dilemma: A Natural History of Four Meals','Michael Pollan',4.17,451),
('Dead as a Doornail (Sookie Stackhouse, #5)','Charlaine Harris',4.01,297),
('The Power of Habit: Why We Do What We Do in Life and Business','Charles Duhigg',4.04,375),
('Zen and the Art of Motorcycle Maintenance: An Inquiry Into Values','Robert M. Pirsig',3.76,540),
('The Raven Boys (The Raven Cycle, #1)','Maggie Stiefvater',4.06,409),
('A Brief History of Time','Stephen Hawking',4.13,198),
('Jonathan Strange & Mr Norrell','Susanna Clarke',3.81,1006),
('All Together Dead (Sookie Stackhouse, #7)','Charlaine Harris',4.05,323),
('From Dead to Worse (Sookie Stackhouse, #8)','Charlaine Harris',4.01,359),
('Left Behind (Left Behind, #1)','Tim LaHaye',3.82,342),
('Snow Crash','Neal Stephenson',4.03,438),
('Dead and Gone (Sookie Stackhouse, #9)','Charlaine Harris',4.01,312),
('Unwind (Unwind, #1)','Neal Shusterman',4.18,335),
('The Shadow of the Wind (The Cemetery of Forgotten Books,  #1)','Carlos Ruiz Zafón',4.25,487),
('All Quiet on the Western Front','Erich Maria Remarque',3.93,296),
('A Farewell to Arms','Ernest Hemingway',3.79,293),
('The 5th Wave (The 5th Wave, #1)','Rick Yancey',4.09,457),
('Misery','Stephen King',4.12,370),
('How to Win Friends and Influence People','Dale Carnegie',4.15,288),
('I Know Why the Caged Bird Sings','Maya Angelou',4.2,246),
('The Glass Castle','Jeannette Walls',4.25,288),
('The House of Hades (The Heroes of Olympus, #4)','Rick Riordan',4.55,597),
('Killing Floor (Jack Reacher, #1)','Lee Child',4.05,525),
('Postmortem (Kay Scarpetta, #1)','Patricia Cornwell',4.01,342),
('The Andromeda Strain','Michael Crichton',3.88,327),
('Thinking, Fast and Slow','Daniel Kahneman',4.1,418),
('The Brief Wondrous Life of Oscar Wao','Junot Díaz',3.9,335),
('Rich Dad, Poor Dad','Robert T. Kiyosaki',3.98,195),
('The Lincoln Lawyer (Mickey Haller, #1, Harry Bosch Universe, #17)','Michael Connelly',4.14,404),
('Choke','Chuck Palahniuk',3.69,293),
('A Confederacy of Dunces','John Kennedy Toole',3.89,416),
('Darkly Dreaming Dexter (Dexter, #1)','Jeff Lindsay',3.9,288),
('Guns, Germs, and Steel: The Fates of Human Societies','Jared Diamond',4,425),
('All the Bright Places','Jennifer Niven',4.19,378),
('It''s Kind of a Funny Story','Ned Vizzini',4.14,444),
('Kitchen Confidential: Adventures in the Culinary Underbelly','Anthony Bourdain',4.01,312),
('When You Are Engulfed in Flames','David Sedaris',4.05,323),
('Timeline','Michael Crichton',3.83,489),
('The Passage (The Passage, #1)','Justin Cronin',4.04,766),
('Man''s Search for Meaning','Viktor E. Frankl',4.34,184),
('When Breath Becomes Air','Paul Kalanithi',4.33,208),
('The 5 Love Languages: The Secret to Love that Lasts','Gary Chapman',4.23,209),
('The City of Ember (Book of Ember, #1)','Jeanne DuPrau',3.85,270),
('Dress Your Family in Corduroy and Denim','David Sedaris',4.09,272),
('City of Heavenly Fire (The Mortal Instruments, #6)','Cassandra Clare',4.47,725),
('Naked','David Sedaris',4.08,304),
('Neuromancer (Sprawl, #1)','William Gibson',3.88,261),
('The Historian','Elizabeth Kostova',3.77,704),
('Before I Go to Sleep','S.J. Watson',3.88,359),
('On the Road','Jack Kerouac',3.64,307),
('Quiet: The Power of Introverts in a World That Can''t Stop Talking','Susan Cain',4.04,337),
('Station Eleven','Emily St. John Mandel',4.02,336),
('A Man Called Ove','Fredrik Backman',4.35,337),
('Red Dragon (Hannibal Lecter, #1)','Thomas Harris',4.02,348),
('Yes Please','Amy Poehler',3.81,329),
('Dead to the World (Sookie Stackhouse, #4)','Charlaine Harris',4.13,291),
('The Secret (The Secret, #1)','Rhonda Byrne',3.64,199),
('Living Dead in Dallas (Sookie Stackhouse, #2)','Charlaine Harris',3.97,291),
('Storm Front (The Dresden Files, #1)','Jim Butcher',4.02,322),
('The Shack','William Paul Young',3.74,252),
('Club Dead (Sookie Stackhouse, #3)','Charlaine Harris',4.03,274),
('The Last Lecture','Randy Pausch',4.25,206),
('The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change','Stephen R. Covey',4.06,372),
('Who Moved My Cheese?','Spencer Johnson',3.75,96),
('Along Came a Spider (Alex Cross, #1)','James Patterson',4.09,435),
('An Abundance of Katherines','John Green',3.62,229),
('The Casual Vacancy','J.K. Rowling',3.28,503),
('City of Fallen Angels (The Mortal Instruments, #4)','Cassandra Clare',4.16,424),
('The Art of Racing in the Rain','Garth Stein',4.2,321),
('Inferno (Robert Langdon, #4)','Dan Brown',3.81,461),
('The Mark of Athena (The Heroes of Olympus, #3)','Rick Riordan',4.46,586),
('Sharp Objects','Gillian Flynn',3.93,254),
('Digital Fortress','Dan Brown',3.62,510),
('Is Everyone Hanging Out Without Me? (And Other Concerns)','Mindy Kaling',3.84,222),
('Red Queen (Red Queen, #1)','Victoria Aveyard',4.08,383),
('Wild: From Lost to Found on the Pacific Crest Trail','Cheryl Strayed',3.97,315),
('Moby-Dick or, The Whale','Herman Melville',3.47,720),
('City of Lost Souls (The Mortal Instruments, #5)','Cassandra Clare',4.3,534),
('The Son of Neptune (The Heroes of Olympus, #2)','Rick Riordan',4.44,521),
('The Tales of Beedle the Bard','J.K. Rowling',4.07,109),
('Deception Point','Dan Brown',3.68,556),
('I Am Number Four (Lorien Legacies, #1)','Pittacus Lore',3.94,440),
('Harry Potter and the Cursed Child - Parts One and Two (Harry Potter, #8)','John Tiffany',3.72,343),
('Fantastic Beasts and Where to Find Them','Newt Scamander',3.97,59),
('Fear and Loathing in Las Vegas','Hunter S. Thompson',4.09,204),
('The Wise Man''s Fear (The Kingkiller Chronicle, #2)','Patrick Rothfuss',4.57,994),
('Outliers: The Story of Success','Malcolm Gladwell',4.11,309),
('Marley and Me: Life and Love With the World''s Worst Dog','John Grogan',4.12,291),
('Artemis Fowl (Artemis Fowl, #1)','Eoin Colfer',3.83,316),
('The Cuckoo''s Calling (Cormoran Strike, #1)','Robert Galbraith',3.84,455),
('The Devil in the White City: Murder, Magic, and Madness at the Fair That Changed America','Erik Larson',3.99,447),
('Treasure Island','Robert Louis Stevenson',3.82,311),
('In Cold Blood','Truman Capote',4.06,343),
('The Godfather (Mario Puzo''s Mafia)','Mario Puzo',4.36,448),
('Flowers for Algernon','Daniel Keyes',4.08,311),
('The Fountainhead','Ayn Rand',3.85,704),
('Never Let Me Go','Kazuo Ishiguro',3.81,288),
('Dune (Dune Chronicles #1)','Frank Herbert',4.2,604),
('One Hundred Years of Solitude','Gabriel García Márquez',4.05,457),
('The Old Man and the Sea','Ernest Hemingway',3.74,132),
('The Return of the King (The Lord of the Rings, #3)','J.R.R. Tolkien',4.51,490),
('The Secret Life of Bees','Sue Monk Kidd',4.02,336),
('Fahrenheit 451','Ray Bradbury',3.98,227),
('The Fellowship of the Ring (The Lord of the Rings, #1)','J.R.R. Tolkien',4.34,398),
('The Metamorphosis','Franz Kafka',3.79,201),
('A Clockwork Orange','Anthony Burgess',3.98,212),
('Ready Player One (Ready Player One, #1)','Ernest Cline',4.31,374),
('Thirteen Reasons Why','Jay Asher',4.01,352),
('The Stranger','Albert Camus',3.96,123),
('Bossypants','Tina Fey',3.95,283),
('The Memory Keeper''s Daughter','Kim Edwards',3.64,401),
('City of Glass (The Mortal Instruments, #3)','Cassandra Clare',4.34,541),
('City of Ashes (The Mortal Instruments, #2)','Cassandra Clare',4.21,453),
('Me Talk Pretty One Day','David Sedaris',3.97,272),
('Middlesex','Jeffrey Eugenides',3.98,529),
('Freakonomics: A Rogue Economist Explores the Hidden Side of Everything (Freakonomics, #1)','Steven D. Levitt',3.94,320),
('Paper Towns','John Green',3.87,305),
('Miss Peregrine’s Home for Peculiar Children (Miss Peregrine’s Peculiar Children, #1)','Ransom Riggs',3.9,352),
('All the Light We Cannot See','Anthony Doerr',4.32,531),
('The Two Towers (The Lord of the Rings, #2)','J.R.R. Tolkien',4.42,322),
('Northern Lights (His Dark Materials, #1)','Philip Pullman',3.95,397),
('The Girl on the Train','Paula Hawkins',3.89,323),
('City of Bones (The Mortal Instruments, #1)','Cassandra Clare',4.12,485),
('A Fine Balance','Rohinton Mistry',4.35,603),
('A Walk in the Woods','Bill Bryson',4.05,397),
('Tuesdays with Morrie','Mitch Albom',4.07,210),
('High Fidelity','Nick Hornby',3.94,340),
('Infinite Jest','David Foster Wallace',4.31,1088),
('Blindness','José Saramago',4.09,326),
('Into the Wild','Jon Krakauer',3.96,207),
('Midnight in the Garden of Good and Evil','John Berendt',3.91,386),
('Snow Falling on Cedars','David Guterson',3.81,460),
('Neverwhere','Neil Gaiman',4.18,370),
('Speak','Laurie Halse Anderson',4,208),
('Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch','Terry Pratchett',4.25,412),
('A Clash of Kings  (A Song of Ice and Fire, #2)','George R.R. Martin',4.41,761),
('Jurassic Park (Jurassic Park, #1)','Michael Crichton',3.98,399),
('Redwall (Redwall, #1)','Brian Jacques',4.11,352),
('The Hobbit','J.R.R. Tolkien',4.25,366),
('The Magus','John Fowles',4.05,656),
('I Am the Messenger','Markus Zusak',4.08,360),
('1984','George Orwell',4.15,328),
('The Wasp Factory','Iain Banks',3.84,192),
('Invisible Monsters Remix','Chuck Palahniuk',4,302),
('In the Woods (Dublin Murder Squad, #1)','Tana French',3.75,429),
('The Secret History','Donna Tartt',4.08,559),
('Harry Potter and the Chamber of Secrets (Harry Potter, #2)','J.K. Rowling',4.39,341),
('The Lost Symbol (Robert Langdon, #3)','Dan Brown',3.67,509),
('I Am Legend and Other Stories','Richard Matheson',3.99,317),
('The Manufactured Identity (Manufactured Identity, #1)','Heath Sommer',3.52,305),
('Tell No One','Harlan Coben',4.11,370),
('The Westing Game','Ellen Raskin',4.03,182),
('Harry Potter and the Goblet of Fire (Harry Potter, #4)','J.K. Rowling',4.53,734),
('Murder on the Orient Express (Hercule Poirot, #10)','Agatha Christie',4.16,322),
('Fight Club','Chuck Palahniuk',4.2,218),
('Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)','J.K. Rowling',4.54,435),
('And Then There Were None','Agatha Christie',4.24,264),
('Angels & Demons  (Robert Langdon, #1)','Dan Brown',3.87,736),
('The Girl Who Played with Fire','Stieg Larsson',4.23,503),
('Cloud Atlas','David Mitchell',4.01,509),
('The Girl Who Kicked the Hornet''s Nest','Stieg Larsson',4.21,563),
('The Curious Incident of the Dog in the Night-Time','Mark Haddon',3.86,226),
('Harry Potter and the Half-Blood Prince (Harry Potter, #6)','J.K. Rowling',4.55,652),
('Harry Potter and the Deathly Hallows (Harry Potter, #7)','J.K. Rowling',4.62,759),
('Looking for Alaska','John Green',4.08,221),
('The Outsiders','S.E. Hinton',4.07,192),
('The Perks of Being a Wallflower','Stephen Chbosky',4.21,213),
('The Fault in Our Stars','John Green',4.25,313),
('Siddhartha','Hermann Hesse',4,152),
('The Road','Cormac McCarthy',3.96,241),
('The Bell Jar','Sylvia Plath',3.98,244),
('One Flew Over the Cuckoo''s Nest','Ken Kesey',4.19,325),
('The Giver (The Giver, #1)','Lois Lowry',4.12,208),
('The Kite Runner','Khaled Hosseini',4.26,371),
('The Stand','Stephen King',4.34,1153),
('Catch-22 (Catch-22, #1)','Joseph Heller',3.98,453),
('Harry Potter and the Sorcerer''s Stone (Harry Potter, #1)','J.K. Rowling',4.45,320),
('Water for Elephants','Sara Gruen',4.07,335),
('Life of Pi','Yann Martel',3.89,460),
('A Game of Thrones (A Song of Ice and Fire, #1)','George R.R. Martin',4.45,848),
('The Catcher in the Rye','J.D. Salinger',3.8,277),
('A Thousand Splendid Suns','Khaled Hosseini',4.34,367),
('Brave New World','Aldous Huxley',3.97,268),
('Lord of the Flies','William Golding',3.65,182),
('Divergent (Divergent, #1)','Veronica Roth',4.23,487),
('The Hunger Games (The Hunger Games, #1)','Suzanne Collins',4.34,374),
('The Picture of Dorian Gray','Oscar Wilde',4.06,254),
('The Da Vinci Code (Robert Langdon, #2)','Dan Brown',3.8,481),
('Wuthering Heights','Emily Brontë',3.83,464),
('The Hitchhiker''s Guide to the Galaxy (Hitchhiker''s Guide to the Galaxy, #1)','Douglas Adams',4.21,216),
('Animal Farm','George Orwell',3.89,122),
('Harry Potter and the Order of the Phoenix (Harry Potter, #5)','J.K. Rowling',4.47,870),
('Fargo Rock City A Heavy Metal Odyssey in Rural North Dakota','Chuck Klosterman',3.79,288),
('The Long Hard Road Out of Hell','Marilyn Manson',3.88,275),
('Killing Yourself to Live: 85% of a True Story','Chuck Klosterman',3.85,245),
('Hammer of the Gods','Stephen Davis',3.83,408),
('Scar Tissue','Anthony Kiedis',4.1,465);
INSERT INTO read (title, author, average_rating, number_of_pages) VALUES
('The Dirt: Confessions of the World''s Most Notorious Rock Band','Neil Strauss',4.16,431),
('Please Kill Me: The Uncensored Oral History of Punk','Legs McNeil',4.16,488),
('You''re Never Weird on the Internet (Almost)','Felicia Day',4.14,272),
('Weird Things Customers Say in Bookshops','Jen Campbell',3.92,268),
('What If?: Serious Scientific Answers to Absurd Hypothetical Questions','Randall Munroe',4.17,303),
('The World Without Us','Alan Weisman',3.79,324),
('The Spirit Catches You and You Fall Down: A Hmong Child, Her American Doctors, and the Collision of Two Cultures','Anne Fadiman',4.15,341),
('The Shock Doctrine: The Rise of Disaster Capitalism','Naomi Klein',4.23,558),
('We Wish to Inform You That Tomorrow We Will Be Killed with Our Families','Philip Gourevitch',4.28,356),
('Predictably Irrational: The Hidden Forces That Shape Our Decisions','Dan Ariely',4.1,280),
('Salt: A World History','Mark Kurlansky',3.73,484),
('The Worst Hard Time: The Untold Story of Those Who Survived the Great American Dust Bowl','Timothy Egan',4.04,312),
('Lies My Teacher Told Me: Everything Your American History Textbook Got Wrong','James W. Loewen',3.96,383),
('The Hot Zone: The Terrifying True Story of the Origins of the Ebola Virus','Richard   Preston',4.1,352),
('Endurance: Shackleton''s Incredible Voyage','Alfred Lansing',4.37,282),
('In the Heart of the Sea: The Tragedy of the Whaleship Essex','Nathaniel Philbrick',4.16,238),
('The Professor and the Madman: A Tale of Murder, Insanity and the Making of the Oxford English Dictionary','Simon Winchester',3.84,242),
('Columbine','Dave Cullen',4.27,417),
('Legend (Legend, #1)','Marie Lu',4.19,305),
('Among the Hidden (Shadow Children, #1)','Margaret Peterson Haddix',3.97,153),
('The Lightning Thief (Percy Jackson and the Olympians, #1)','Rick Riordan',4.23,375),
('Good to Great: Why Some Companies Make the Leap... and Others Don''t','James C. Collins',4.05,320),
('The Bourne Identity (Jason Bourne, #1)','Robert Ludlum',3.99,566),
('The Postman','David Brin',3.88,323),
('White Noise','Don DeLillo',3.86,320),
('The Stranger Beside Me: Ted Bundy The Shocking Inside Story','Ann Rule',4.13,560),
('Gorky Park (Arkady Renko, #1)','Martin Cruz Smith',4.04,433),
('Less Than Zero','Bret Easton Ellis',3.59,208),
('The Satanic Verses','Salman Rushdie',3.71,561),
('Holy Blood, Holy Grail','Michael Baigent',3.47,496),
('The Alchemist','Paulo Coelho',3.83,197),
('Lies & the Lying Liars Who Tell Them: A Fair & Balanced Look at the Right','Al Franken',3.81,421),
('Critical Failures','Robert Bevan',3.81,316),
('Mountain Man Dance Moves: The McSweeney''s Book of Lists','McSweeney''s Publishing',4.07,224),
('Wonder Boys','Michael Chabon',3.93,383),
('Florida Roadkill (Serge Storms, #1)','Tim Dorsey',3.75,288),
('John Dies at the End (John Dies at the End, #1)','David Wong',3.91,362),
('When Will Jesus Bring the Pork Chops?','George Carlin',3.84,295),
('HELP!  A Bear is Eating Me!','Mykle Hansen',3.5,132),
('The Secret Life of Walter Mitty and Other Pieces','James Thurber',3.88,416),
('Tourist Season','Carl Hiaasen',3.95,404),
('The Gun Seller','Hugh Laurie',3.69,340),
('Forrest Gump (Forrest Gump, #1)','Winston Groom',4.06,248),
('The Partly Cloudy Patriot','Sarah Vowell',3.89,197),
('The Sex Lives of Cannibals: Adrift in the Equatorial Pacific','J. Maarten Troost',3.87,272),
('Everything Is Illuminated','Jonathan Safran Foer',3.9,276),
('Apathy and Other Small Victories','Paul Neilan',3.84,240),
('I Was Told There''d Be Cake','Sloane Crosley',3.45,230),
('The Amulet of Samarkand (Bartimaeus, #1)','Jonathan Stroud',4,462),
('Magical Thinking: True Stories','Augusten Burroughs',3.97,304),
('Thank You for Smoking','Christopher Buckley',3.92,272),
('I Love Everybody (and Other Atrocious Lies)','Laurie Notaro',3.97,228),
('Queen of the Road: The True Tale of 47 States, 22,000 Miles, 200 Shoes, 2 Cats, 1 Poodle, a Husband, and a Bus with a Will of Its Own','Doreen Orion',3.44,304),
('I Hope They Serve Beer in Hell (Tucker Max, #1)','Tucker Max',3.51,288),
('The Areas of My Expertise: An Almanac of Complete World Knowledge Compiled with Instructive Annotation and Arranged in Useful Order','John Hodgman',3.81,256),
('Dry','Augusten Burroughs',4.01,293),
('I Like You: Hospitality Under the Influence','Amy Sedaris',3.87,304),
('Possible Side Effects','Augusten Burroughs',3.98,291),
('Brain Droppings','George Carlin',4.12,272),
('Napalm & Silly Putty','George Carlin',4.12,269),
('Nature Girl','Carl Hiaasen',3.62,306),
('Still Life with Woodpecker','Tom Robbins',4.04,277),
('Native Tongue (Skink, #2)','Carl Hiaasen',3.94,437),
('Barrel Fever: Stories and Essays','David Sedaris',3.78,196),
('Skin Tight (Mick Stranahan, #1)','Carl Hiaasen',3.96,432),
('My Life and Hard Times','James Thurber',4.14,106),
('My Horizontal Life: A Collection of One-Night Stands','Chelsea Handler',3.79,213),
('Our Dumb Century: The Onion Presents 100 Years of Headlines from America''s Finest News Source','The Onion',4.18,164),
('Sick Puppy','Carl Hiaasen',3.88,464),
('Sex, Drugs, and Cocoa Puffs: A Low Culture Manifesto','Chuck Klosterman',3.75,272),
('Straight Man','Richard Russo',4.02,391),
('Big Trouble','Dave Barry',3.81,317),
('Skinny Dip','Carl Hiaasen',3.79,496),
('If Life Is a Bowl of Cherries What Am I Doing in the Pits?','Erma Bombeck',4.07,224),
('SantaLand Diaries','David Sedaris',4.33,138),
('Freaks I''ve Met','Donald Jans',4.44,208),
('Practical Demonkeeping (Pine Cove, #1)','Christopher Moore',3.82,256),
('Running with Scissors','Augusten Burroughs',3.7,304),
('The Maze Runner (The Maze Runner, #1)','James Dashner',4.03,384),
('Origin (Robert Langdon, #5)','Dan Brown',3.85,461),
('The Girl with the Dragon Tattoo (Millennium, #1)','Stieg Larsson',4.12,465),
('Fall of Giants (The Century Trilogy, #1)','Ken Follett',4.26,985),
('Eats, Shoots & Leaves: The Zero Tolerance Approach to Punctuation','Lynne Truss',3.87,209),
('The Perfect Storm: A True Story of Men Against the Sea','Sebastian Junger',4.08,301),
('The Sirens of Titan','Kurt Vonnegut',4.16,224),
('Cosmos','Carl Sagan',4.35,384),
('The Moon is a Harsh Mistress','Robert A. Heinlein',4.17,288),
('The Story of Edgar Sawtelle','David Wroblewski',3.6,566),
('Hoot','Carl Hiaasen',3.81,292),
('Seriously... I''m Kidding','Ellen DeGeneres',3.72,241),
('Animal, Vegetable, Miracle: A Year of Food Life','Barbara Kingsolver',4.04,370),
('Getting Things Done: The Art of Stress-Free Productivity','David    Allen',3.99,267),
('Kane and Abel (Kane and Abel, #1)','Jeffrey Archer',4.27,592),
('American Sniper: The Autobiography of the Most Lethal Sniper in U.S. Military History','Chris Kyle',3.97,528),
('A Stolen Life','Jaycee Dugard',3.89,273),
('The Long Walk','Richard Bachman',4.11,370),
('Let It Snow: Three Holiday Romances','John Green',3.82,352),
('City of Thieves','David Benioff',4.28,258),
('The Color of Water: A Black Man''s Tribute to His White Mother','James McBride',4.07,291),
('Her Fearful Symmetry','Audrey Niffenegger',3.24,406),
('The World Is Flat: A Brief History of the Twenty-first Century','Thomas L. Friedman',3.67,616),
('Beautiful Chaos (Caster Chronicles, #3)','Kami Garcia',3.95,516),
('A Dog''s Purpose (A Dog''s Purpose, #1)','W. Bruce Cameron',4.35,319),
('The 4-Hour Workweek','Timothy Ferriss',3.85,308),
('The Year of the Flood  (MaddAddam, #2)','Margaret Atwood',4.06,431),
('Thus Spoke Zarathustra','Friedrich Nietzsche',4.05,327),
('Lucky','Alice Sebold',3.77,243),
('Survivor','Chuck Palahniuk',3.93,289),
('The Big Sleep (Philip Marlowe, #1)','Raymond Chandler',4.03,231),
('Sapiens: A Brief History of Humankind','Yuval Noah Harari',4.44,443),
('Winter of the World (The Century Trilogy #2)','Ken Follett',4.3,960),
('House of Leaves','Mark Z. Danielewski',4.13,705),
('Mystic River','Dennis Lehane',4.18,416),
('The Darkest Minds (The Darkest Minds, #1)','Alexandra Bracken',4.24,488),
('Let''s Explore Diabetes with Owls','David Sedaris',3.8,275),
('Me and Earl and the Dying Girl','Jesse Andrews',3.58,295),
('The Lost World (Jurassic Park, #2)','Michael Crichton',3.74,448),
('Holidays on Ice','David Sedaris',3.94,176),
('The Psychopath Test: A Journey Through the Madness Industry','Jon Ronson',3.92,275),
('The Day of the Jackal','Frederick Forsyth',4.25,384),
('Helter Skelter: The True Story of the Manson Murders','Vincent Bugliosi',4.01,689),
('The Eyre Affair (Thursday Next, #1)','Jasper Fforde',3.91,374),
('The Deep End of the Ocean (Cappadora Family, #1)','Jacquelyn Mitchard',3.85,464),
('Watchers','Dean Koontz',4.16,624),
('Brain on Fire: My Month of Madness','Susannah Cahalan',4.01,250),
('Seabiscuit: An American Legend','Laura Hillenbrand',4.2,457),
('Between Shades of Gray','Ruta Sepetys',4.36,344),
('In a Dark, Dark Wood','Ruth Ware',3.66,352),
('A Beautiful Mind','Sylvia Nasar',4.12,464),
('No Country for Old Men','Cormac McCarthy',4.13,309),
('Beautiful Darkness (Caster Chronicles, #2)','Kami Garcia',3.84,503),
('A Long Way Gone: Memoirs of a Boy Soldier','Ishmael Beah',4.14,229),
('Rework','Jason Fried',3.93,279),
('Tell the Wolves I''m Home','Carol Rifka Brunt',4.04,360),
('The Blind Assassin','Margaret Atwood',3.95,637),
('People of the Book','Geraldine Brooks',4.01,372),
('Wool Omnibus (Silo, #1)','Hugh Howey',4.24,509),
('The Audacity of Hope: Thoughts on Reclaiming the American Dream','Barack Obama',3.71,375),
('The Girls','Emma Cline',3.48,355),
('Think and Grow Rich','Napoleon Hill',4.17,233),
('All Creatures Great and Small','James Herriot',4.31,448),
('The Surgeon (Rizzoli & Isles, #1)','Tess Gerritsen',4.1,416),
('Surely You''re Joking, Mr. Feynman!: Adventures of a Curious Character','Richard Feynman',4.29,391),
('The Dinner','Herman Koch',3.22,292),
('This is Where I Leave You','Jonathan Tropper',3.88,339),
('Luckiest Girl Alive','Jessica Knoll',3.48,352),
('The Alienist (Dr. Laszlo Kreizler, #1)','Caleb Carr',4.05,498),
('The Couple Next Door','Shari Lapena',3.75,308),
('The Year of Magical Thinking','Joan Didion',3.87,227),
('The Selfish Gene','Richard Dawkins',4.12,360),
('The Happiness Project: Or Why I Spent a Year Trying to Sing in the Morning, Clean My Closets, Fight Right, Read Aristotle, and Generally Have More Fun','Gretchen Rubin',3.58,301),
('Eye of the Needle','Ken Follett',4.17,368),
('Naked in Death (In Death #1)','J.D. Robb',4.12,306),
('We Need to Talk About Kevin','Lionel Shriver',4.07,400),
('Reconstructing Amelia','Kimberly McCreight',3.82,382),
('Team of Rivals: The Political Genius of Abraham Lincoln','Doris Kearns Goodwin',4.29,916),
('The Black Echo (Harry Bosch, #1, Harry Bosch Universe, #1)','Michael Connelly',4.09,482),
('Stiff: The Curious Lives of Human Cadavers','Mary Roach',4.05,320),
('The Big Short: Inside the Doomsday Machine','Michael   Lewis',4.26,320),
('Modern Romance','Aziz Ansari',3.85,279),
('The Girl With All the Gifts (The Girl With All the Gifts series)','M.R. Carey',3.93,461),
('Flowers in the Attic (Dollanganger, #1)','V.C. Andrews',3.8,389),
('The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics','Daniel James Brown',4.33,416),
('The Knife of Never Letting Go (Chaos Walking, #1)','Patrick Ness',3.96,479),
('Dark Matter','Blake Crouch',4.1,342),
('Steal Like an Artist: 10 Things Nobody Told You About Being Creative','Austin Kleon',3.88,160),
('The Bone Collector (Lincoln Rhyme, #1)','Jeffery Deaver',4.18,528),
('Trainspotting','Irvine Welsh',4.08,430),
('The Underground Railroad','Colson Whitehead',4.03,306),
('Between the World and Me','Ta-Nehisi Coates',4.4,152),
('The Autobiography of Malcolm X','Malcolm X',4.29,466),
('Born to Run: A Hidden Tribe, Superathletes, and the Greatest Race the World Has Never Seen','Christopher McDougall',4.28,287),
('Life As We Knew It (Last Survivors, #1)','Susan Beth Pfeffer',3.89,337),
('The Jungle','Upton Sinclair',3.72,335),
('Plain Truth','Jodi Picoult',3.97,405),
('Hillbilly Elegy: A Memoir of a Family and Culture in Crisis','J.D. Vance',3.95,272),
('The Man Who Mistook His Wife for a Hat and Other Clinical Tales','Oliver Sacks',4.05,243),
('Steelheart (The Reckoners, #1)','Brandon Sanderson',4.16,386),
('Dreams from My Father: A Story of Race and Inheritance','Barack Obama',3.82,453),
('Walden','Henry David Thoreau',3.79,352),
('Roots: The Saga of an American Family','Alex Haley',4.42,729),
('The Four Agreements: A Practical Guide to Personal Freedom','Miguel Ruiz',4.13,168),
('The Circle','Dave Eggers',3.45,493),
('The Power of Now: A Guide to Spiritual Enlightenment','Eckhart Tolle',4.11,229),
('1776','David McCullough',4.06,386),
('Clear and Present Danger (Jack Ryan Universe, #6)','Tom Clancy',4.08,688),
('The Hundred-Year-Old Man Who Climbed Out of the Window and Disappeared','Jonas Jonasson',3.82,396),
('Sphere','Michael Crichton',3.78,371),
('Behind Closed Doors','B.A. Paris',3.93,293),
('Dead Reckoning (Sookie Stackhouse, #11)','Charlaine Harris',3.77,336),
('Sh*t My Dad Says','Justin Halpern',3.98,159),
('Mr. Penumbra''s 24-Hour Bookstore (Mr. Penumbra''s 24-Hour Bookstore, #1)','Robin Sloan',3.75,288),
('The Blood of Olympus (The Heroes of Olympus, #5)','Rick Riordan',4.42,516),
('Schindler''s List','Thomas Keneally',4.34,429),
('Let''s Pretend This Never Happened: A Mostly True Memoir','Jenny  Lawson',3.9,318),
('Men Are from Mars, Women Are from Venus','John Gray',3.53,368),
('Six of Crows (Six of Crows, #1)','Leigh Bardugo',4.46,465),
('Red Rising (Red Rising, #1)','Pierce Brown',4.26,382),
('The Lies of Locke Lamora (Gentleman Bastard, #1)','Scott Lynch',4.3,499),
('Dead in the Family (Sookie Stackhouse, #10)','Charlaine Harris',3.88,311),
('A is for Alibi (Kinsey Millhone, #1)','Sue Grafton',3.82,307),
('Jaws','Peter Benchley',3.97,320),
('Congo','Michael Crichton',3.56,480),
('A Monster Calls','Patrick Ness',4.37,226),
('The Man in the High Castle','Philip K. Dick',3.65,259),
('Needful Things','Stephen King',3.88,790);